---
- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      - fish
      - fzf

- name: Create directories
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ home }}/.config/fish"
    - "{{ home }}/.config/fish/functions/"

- name: "Clone repositories"
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "{{ home }}/{{ item.dest }}"
    update: no
  with_items:
    - repo: mrkuz/dotfiles
      dest: etc/dotfiles.git

- name: Link dotfiles
  become: yes
  become_user: "{{ user }}"
  file:
    src: "{{ home }}/etc/dotfiles.git/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
  with_items:
    - bin/fsh
    - .config/fish/config.fish
    - .config/fish/fish_variables
    - .config/fish/functions/fish_prompt.fish
    - .config/fish/functions/note.fish
    - .config/fish/functions/scratch.fish
    - .config/fish/functions/todo.fish
    - .config/fish/functions/x11d.fish

- name: Install fisher
  become: yes
  become_user: "{{ user }}"
  get_url:
    url: https://github.com/jorgebucaran/fisher/blob/master/fisher.fish
    dest: "{{ home}}/.config/fish/functions/fisher.fish"
    mode: 0744

- name: Set up fish
  become: yes
  become_user: "{{ user }}"
  shell: |
    set -U fish_greeting
    fisher add jethrokuan/fzf
    fisher add evanlucas/fish-kubectl-completions
    set -e FZF_COMPLETE
    echo OK > {{ home }}/.var/fish.done
  args:
    executable: /usr/bin/fish
    creates: "{{ home }}/.var/fish.done"
