---
- name: Create directories
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ home }}/bin"
    - "{{ home }}/.config/fish"
    - "{{ home }}/.config/fish/functions/"

- name: "Clone repositories"
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "{{ home }}/{{ item.dest }}"
    update: no
  with_items:
    - repo: mrkuz/dotfiles
      dest: etc/dotfiles.git
  register: r_fish_clone_repos

- name: Link dotfiles
  become: yes
  become_user: "{{ user }}"
  file:
    src: "{{ home }}/etc/dotfiles.git/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - .config/fish/config.fish
    - .config/fish/fish_variables
    - .config/fish/functions/fish_prompt.fish
    # - .config/fish/functions/note.fish
    # - .config/fish/functions/todo.fish
  when: r_fish_clone_repos is not skipped

- name: Install fisher
  become: yes
  become_user: "{{ user }}"
  shell: curl https://git.io/fisher -sLo {{ home }}/.config/fish/functions/fisher.fish
  args:
    warn: false
    creates: "{{ home }}/.config/fish/functions/fisher.fish"
  register: r_fish_install_fisher

- name: Set up fish
  become: yes
  become_user: "{{ user }}"
  shell: |
    set -U fish_greeting
    fisher add evanlucas/fish-kubectl-completions
    echo OK > {{ home }}/.var/fish.done
  args:
    executable: "{{ home }}/.nix-profile/bin/fish"
    creates: "{{ home }}/.var/fish.done"
  when: r_fish_install_fisher is not skipped
