- name: Add user
  become: yes
  user:
    name: "{{ user }}"
    comment: "{{ fullName }}"
    shell: /bin/bash
    groups: adm,cdrom,dip,lpadmin,lxd,plugdev,sudo
    append: yes
  notify: Reset password
