---
- name: Create directories
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ home }}/Backup"
    - "{{ home }}/bin"
    - "{{ home }}/Documents"
    - "{{ home }}/Downloads/Torrent"
    - "{{ home }}/etc"
    - "{{ home }}/Games/Steam"
    - "{{ home }}/Music"
    - "{{ home }}/Notes"
    - "{{ home }}/opt/plantuml"
    - "{{ home }}/org/calendar"
    - "{{ home }}/org/lists"
    - "{{ home }}/org/mobile"
    - "{{ home }}/org/projects"
    - "{{ home }}/Pictures"
    - "{{ home }}/Scripts"
    - "{{ home }}/Shared"
    - "{{ home }}/src"
    - "{{ home }}/tmp"
    - "{{ home }}/Videos"
    - "{{ home }}/Workspace"
    - "{{ home }}/.android"
    - "{{ home }}/.emacs.d/local/straight"
    - "{{ home }}/.gradle/wrapper"
    - "{{ home }}/.m2"
    - "{{ home }}/.vagrant.d"
    - "{{ home }}/.var"
    - "{{ home }}/.ansible/tmp"

- name: Create user data directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  with_items:
    - "/data/user/{{ user }}"
    - "/data/user/{{ user }}/opt"
    - "/data/user/{{ user }}/Downloads"
    - "/data/user/{{ user }}/Games"
    - "/data/user/{{ user }}/VirtualBox VMs"
    - "/data/user/{{ user }}/.android/avd"
    - "/data/user/{{ user }}/.emacs.d/.local/straight/repos"
    - "/data/user/{{ user }}/.gradle/wrapper/dists"
    - "/data/user/{{ user }}/.m2/repository"
    - "/data/user/{{ user }}/.vagrant.d/boxes"

- name: Link data directories
  become: yes
  become_user: "{{ user }}"
  file:
    src: "/data/user/{{ user }}/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
  with_items:
    - "opt"
    - "Downloads"
    - "Games"
    - "VirtualBox VMs"
    - ".android/avd"
    - ".emacs.d/.local/straight/repos"
    - ".gradle/wrapper/dists"
    - ".m2/repository"
    - ".vagrant.d/boxes"

- name: "Clone repositories"
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "{{ home }}/{{ item.dest }}"
    update: no
  with_items:
    - repo: abhigenie92/unattended_upgrades_repos
      dest: src/unattended_upgrades_repos
    - repo: mrkuz/ansible
      dest: etc/ansible
    - repo: mrkuz/dotfiles
      dest: etc/dotfiles.git
    - repo: mrkuz/vagrant-k3s
      dest: src/vagrant-k3s
  register: r_user_clone_repos

- name: Link dotfiles
  become: yes
  become_user: "{{ user }}"
  file:
    src: "{{ home }}/etc/dotfiles.git/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
  with_items:
    - .bashrc.local
    - .eclipse-java-style.xml
    - .gitconfig
    - .gradle/gradle.properties
    - .inputrc
    - .tmux.conf
    - .shortcuts.json
  when: r_user_clone_repos is not skipped

- name: Configure bash
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: "{{ home }}/.bashrc"
    line: . ~/.bashrc.local
