---
- name: Create directories
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ home }}/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "bin"
    - "etc"
    - "org/calendar"
    - "org/lists"
    - "org/mobile"
    - "org/projects"
    - "tmp"
    - "Documents"
    - "Downloads"
    - "Games"
    - "Music"
    - "Notes"
    - "opt"
    - "Pictures"
    - "Scripts"
    - "Shared"
    - "src"
    - "Videos"
    - "VirtualBox VMs"
    - "Workspace"
    - ".android"
    - ".config/nixpkgs"
    - ".config/systemd/user"
    - ".emacs.d/.local/straight"
    - ".gradle/wrapper"
    - ".m2"
    - ".vagrant.d"
    - ".var"
    - ".ansible/tmp"
    - ".vscode/DevOps"
    - ".vscode/Java"
    - ".vscode/JavaScript"

- name: Setup user data directories
  include_tasks: setup_data_dir.yml
  vars:
    directory: "{{ item }}"
  with_items:
    - "Backup"

- name: "Clone repositories"
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "{{ home }}/{{ item.dest }}"
    update: no
  with_items:
    - repo: mrkuz/ansible
      dest: etc/ansible
    - repo: mrkuz/dotfiles
      dest: etc/dotfiles.git
    - repo: mrkuz/nixos
      dest: etc/nixos
    - repo: mrkuz/nix-shell
      dest: etc/nix-shell
    - repo: mrkuz/nix-scripts
      dest: src/nix-scripts
    - repo: mrkuz/vagrant-k3s
      dest: src/vagrant-k3s
    - repo: mrkuz/dockerfiles
      dest: src/dockerfiles
  register: r_user_clone_repos

- name: Link dotfiles
  become: yes
  become_user: "{{ user }}"
  file:
    src: "{{ home }}/etc/dotfiles.git/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - .bashrc.local
    - .config/nixpkgs/config.nix
    - .config/nixpkgs/home.nix
    - .config/systemd/user/conky.service
    - .conkyrc
    - .eclipse-java-style.xml
    - .gitconfig
    - .gradle/gradle.properties
    - .inputrc
    - .local/share/applications/cups.desktop
    - .local/share/applications/conky.desktop
    - .local/share/applications/hplip.desktop
    - .local/share/applications/htop.desktop
    - .local/share/applications/nixos-manual.desktop
    - .local/share/applications/nvidia-settings.desktop
    - .local/share/applications/xpra-gui.desktop
    - .local/share/applications/xterm.desktop
    - .tmux.conf
    - .shortcuts.json
  when: r_user_clone_repos is not skipped

- name: Link scripts
  become: yes
  become_user: "{{ user }}"
  file:
    src: "{{ home }}/src/nix-scripts/{{ item }}"
    dest: "{{ home }}/Scripts/{{ item }}"
    state: link
    force: yes
  with_items:
    - update.sh
    - clean-up.sh
  when: r_user_clone_repos is not skipped

- name: Initialize home-manager
  become: yes
  become_user: "{{ user }}"
  shell: |
      export NIX_PATH="nixpkgs=/nix/nixpkgs nixos-config=/etc/nixos/configuration.nix"
      home-manager switch
  args:
    executable: /run/current-system/sw/bin/bash
    creates: "{{ home }}/.nix-profile"

- name: Configure bash
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: "{{ home }}/.bashrc"
    line: . ~/.bashrc.local

- name: Enable services
  become: yes
  become_user: "{{ user }}"
  systemd:
    daemon-reload: true
    name: conky.service
    scope: user
    enabled: true
