---
- name: Create directories
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ home }}/.config"
    - "{{ home }}/.config/Code"
    - "{{ home }}/.config/Code/User"
    - "{{ home }}/.vscode"
    - "{{ home }}/.vscode/DevOps"
    - "{{ home }}/.vscode/DevOps/extensions"
    - "{{ home }}/.vscode/DevOps/User"
    - "{{ home }}/.vscode/Java"
    - "{{ home }}/.vscode/Java/extensions"
    - "{{ home }}/.vscode/Java/User"
    - "{{ home }}/.vscode/JavaScript"
    - "{{ home }}/.vscode/JavaScript/extensions"
    - "{{ home }}/.vscode/JavaScript/User"

- name: "Clone repositories"
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "{{ home }}/{{ item.dest }}"
    update: no
  with_items:
    - repo: mrkuz/dotfiles
      dest: etc/dotfiles.git

- name: Link dotfiles
  become: yes
  become_user: "{{ user }}"
  file:
    src: "{{ home }}/etc/dotfiles.git/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
  with_items:
    - .config/Code/User/keybindings.json
    - .config/Code/User/settings.json
    - .eclipse-java-style.xml

- name: Set up vscode profiles
  become: yes
  become_user: "{{ user }}"
  file:
    src: "{{ home }}/etc/dotfiles.git/.config/Code/User/{{ item.file }}"
    dest: "{{ home }}/.vscode/{{ item.profile }}/User/{{ item.file }}"
    state: link
  with_items:
    - { profile: DevOps, file: settings.json }
    - { profile: DevOps, file: keybindings.json }
    - { profile: Java, file: settings.json }
    - { profile: Java, file: keybindings.json }
    - { profile: JavaScript, file: settings.json }
    - { profile: JavaScript, file: keybindings.json }
