---
- name: Create directories
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ home }}/.config"
    - "{{ home }}/.config/Code"
    - "{{ home }}/.config/Code/User"
    - "{{ home }}/.vscode"

- name: "Clone repositories"
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "{{ home }}/{{ item.dest }}"
    update: no
  with_items:
    - repo: mrkuz/dotfiles
      dest: etc/dotfiles.git
  register: r_vscode_clone_repos

- name: Link dotfiles
  become: yes
  become_user: "{{ user }}"
  file:
    src: "{{ home }}/etc/dotfiles.git/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
  with_items:
    - .config/Code/User/keybindings.json
    - .config/Code/User/settings.json
    - .eclipse-java-style.xml
  when: r_vscode_clone_repos is not skipped

- name: Set up profile
  include_tasks: setup_profile.yml
  vars:
    profile: "{{ outer_item }}"
  loop_control:
    loop_var: outer_item
  loop:
    - name: Java
      extension_ids:
        - CoenraadS.bracket-pair-colorizer
        - lfs.vscode-emacs-friendly
        - rokoroku.vscode-theme-darcula
        - vscode-icons-team.vscode-icons
        #
        - GabrielBB.vscode-lombok
        - Pivotal.vscode-boot-dev-pack
        - redhat.vscode-xml
        - vscjava.vscode-java-pack
    - name: JavaScript
      extension_ids:
        - CoenraadS.bracket-pair-colorizer
        - lfs.vscode-emacs-friendly
        - rokoroku.vscode-theme-darcula
        - vscode-icons-team.vscode-icons
        #
        - mubaidr.vuejs-extension-pack
        - naumovs.color-highlight
    - name: DevOps
      extension_ids:
        - CoenraadS.bracket-pair-colorizer
        - lfs.vscode-emacs-friendly
        - rokoroku.vscode-theme-darcula
        - vscode-icons-team.vscode-icons
        #
        - ms-azuretools.vscode-docker
        - ms-kubernetes-tools.vscode-kubernetes-tools
        - vscoss.vscode-ansible
