---
- name: Add repositories
  become: yes
  apt_repository:
    repo: "ppa:graphics-drivers/ppa"

- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      - nvidia-driver-440
      - nvidia-settings
      - vulkan-utils

- name: Remove conflicting packages
  become: yes
  apt:
    state: absent
    purge: yes
    name:
      - mesa-vulkan-drivers
      - mesa-vulkan-drivers:i386

- name: Clean up
  become: yes
  apt:
    autoremove: yes
    autoclean: yes
