---
- name: Create a logical volumes
  become: true
  lvol:
    vg: "{{ volume_group}}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
  with_items:
    - { name: home, size: 200G }
    - { name: snap, size: 20G }
    - { name: flatpak, size: 20G }
    - { name: docker, size: 20G }
    - { name: docker-home-overlay, size: 10G }
    - { name: swap, size: 1G }

- name: Create filesystems
  become: true
  filesystem:
    fstype: "{{ item.type }}"
    dev: "/dev/{{ volume_group }}/{{ item.name }}"
  with_items:
    - { name: home, type: ext4 }
    - { name: snap, type: ext4 }
    - { name: flatpak, type: ext4 }
    - { name: docker, type: ext4 }
    - { name: docker-home-overlay, type: ext4 }
    - { name: swap, type: swap }

- name: Mount volumes
  become: true
  mount:
    path: "{{ item.target }}"
    src: "/dev/{{ volume_group }}/{{ item.name }}"
    fstype: "{{ item.type }}"
    passno: "{{ item.pass }}"
    state: mounted
  with_items:
    - { name: snap, type: ext4, target: /var/lib/snapd, pass: 2 }
    - { name: flatpak, type: ext4, target: /var/lib/flatpak, pass: 2 }
    - { name: docker, type: ext4, target: /var/lib/docker, pass: 2 }
    - {
        name: docker-home-overlay,
        type: ext4,
        target: /data/docker-home-overlay,
        pass: 2,
      }

- name: Mount home
  become: true
  mount:
    path: /home
    src: "/dev/{{ volume_group }}/home"
    fstype: ext4
    passno: "2"
    state: present

- name: Mount swap
  become: yes
  lineinfile:
    path: /etc/fstab
    regex: "^/dev/{{ volume_group }}/swap"
    line: "/dev/{{ volume_group }}/swap none swap sw 0 0"
  register: r_mount_swap

- name: Activate swap
  become: yes
  command: swapon "/dev/{{ volume_group }}/swap"
  when: r_mount_swap.changed

- name: Mount AUFS
  become: true
  mount:
    path: /data/docker-home
    src: none
    fstype: aufs
    passno: "2"
    state: mounted
    opts: dirs=/data/docker-home-overlay=rw:/home=ro,x-systemd.requires-mounts-for=/home
