---
- name: Add repositories
  become: yes
  apt_repository:
    repo: "ppa:lutris-team/lutris"

- name: Install packages
  become: yes
  apt:
    update_cache: yes
    names:
      - lutris
      - steam
      - steam-devices
      - wine64
