---
- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      - chrome-gnome-shell
      - gnome-session
      - gnome-shell-extension-appindicator
      - gnome-tweaks
      - gnome-shell-pomodoro
      - nautilus

- name: Get gnome shell version
  shell: gnome-shell --version | sed 's/GNOME Shell //'
  register: gnomeShellVersion
  changed_when: no

- name: Get extension infos
  uri:
    url: "https://extensions.gnome.org/extension-info/?pk={{ item }}&shell_version={{ gnomeShellVersion.stdout }}"
    return_content: yes
  with_items:
    - 307 # Dash to dock
    - 448 # Remove rounded corners
    - 1007 # Window Is Ready - Notification Remover
    - 1765 # Transparent top bar
    - 1144 # Shortcuts
    - 973 # Switcher
    - 19 # User themes
    - 1683 # Draw on your screen
  register: gnomeExtensionInfos

- name: Install extensions
  include_tasks: install_extension.yml
  vars:
    info: "{{ item.json }}"
  loop: "{{ gnomeExtensionInfos.results }}"
