---
- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      - chrome-gnome-shell
      - gnome-session
      - gnome-shell-extension-appindicator
      - gnome-tweaks
      - gnome-shell-pomodoro
      - nautilus

- name: Get gnome shell version
  shell: gnome-shell --version | sed 's/GNOME Shell //'
  register: r_gnome_shell_version
  changed_when: no

- name: Install extensions
  include_tasks: install_extension.yml
  vars:
    gnome_shell_version: "{{ r_gnome_shell_version.stdout }}"
    extension_id: "{{ item }}"
  with_items:
    - 307 # Dash to dock
    - 448 # Remove rounded corners
    - 1007 # Window Is Ready - Notification Remover
    - 1765 # Transparent top bar
    - 1144 # Shortcuts
    - 973 # Switcher
    - 19 # User themes
    - 1683 # Draw on your screen

- name: Set up gnome
  become: yes
  become_user: "{{ user }}"
  block:
    - name: Create directory
      file:
        path: "{{ home }}/.var"
        state: directory
        mode: 0755
    - name: Copy dconf file
      copy:
        src: dconf
        dest: "{{ home }}/.var/dconf"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
    - name: Import settings
      shell: |
        export $(dbus-launch)
        dconf load / < {{ home }}/.var/dconf
        echo OK > {{ home }}/.var/dconf.done
      args:
        executable: /usr/bin/bash
        creates: "{{ home }}/.var/dconf.done"
