---
- name: Get gnome shell version
  shell: gnome-shell --version | sed 's/GNOME Shell //'
  register: r_gnome_shell_version
  changed_when: no
  check_mode: no

- name: Install extensions
  include_tasks: install_extension.yml
  vars:
    gnome_shell_version: "{{ r_gnome_shell_version.stdout }}"
    extension_id: "{{ item }}"
  with_items:
    - 448 # Remove rounded corners
    - 1007 # Window Is Ready - Notification Remover
    - 1708 # Transparent top bar
    - 1144 # Shortcuts

#- name: Set up gnome
#  become: yes
#  become_user: "{{ user }}"
#  block:
#    - name: Create directory
#      file:
#        path: "{{ home }}/.var"
#        state: directory
#        mode: 0755
#    - name: Copy dconf file
#      copy:
#        src: dconf
#        dest: "{{ home }}/.var/dconf"
#        owner: "{{ user }}"
#        group: "{{ user }}"
#        mode: "0644"
#    - name: Import settings
#      shell: |
#        export $(dbus-launch)
#        dconf load / < {{ home }}/.var/dconf
#        echo OK > {{ home }}/.var/dconf.done
#      args:
#        executable: /run/current-system/sw/bin/bash
#        creates: "{{ home }}/.var/dconf.done"
