---
- name: Install snaps
  become: yes
  snap:
    classic: true
    name:
      - google-cloud-sdk
      - helm
      - juju
      - kubectl
      - microk8s
  notify: Assign microk8s group

- name: Flush handlers
  meta: flush_handlers

- name: Set up microk8s
  become: yes
  become_user: "{{ user }}"
  block:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ home }}/.kube"
        - "{{ home }}/.var"
    - name: Set up microk8s
      shell: |
        microk8s.enable dns &
        microk8s.kubectl config view --raw > {{ home }}/.kube/microk8s
        echo OK > {{ home }}/.var/microk8s.done
      args:
        executable: /usr/bin/bash
        creates: "{{ home }}/.var/microk8s.done"
