---
- name: Assign microk8s group
  become: yes
  user:
    name: "{{ user }}"
    groups:
      - microk8s
    append: yes

- name: Set up microk8s
  become: yes
  become_user: "{{ user }}"
  block:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ home }}/.kube"
        - "{{ home }}/.var"
    - name: Set up microk8s
      shell: |
        microk8s enable dns &
        microk8s kubectl config view --raw > {{ home }}/.kube/microk8s
        echo OK > {{ home }}/.var/microk8s.done
      args:
        executable: /usr/bin/bash
        creates: "{{ home }}/.var/microk8s.done"
