---
- name: "Clone repositories"
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "{{ home }}/{{ item.dest }}"
    update: no
  with_items:
    - repo: hakimel/reveal.js
      dest: opt/reveal.js
    - repo: hlissner/doom-emacs
      dest: .emacs.d
    - repo: mrkuz/doom.d
      dest: etc/doom.d
  register: r_emacs_clone_repos

- name: Set up doom
  become: yes
  become_user: "{{ user }}"
  block:
    - name: Create directory
      file:
        path: "{{ home }}/bin"
        state: directory
        mode: 0755
    - name: "Link doom directory"
      file:
        src: "{{ home }}/etc/doom.d"
        dest: "{{ home }}/.doom.d"
        state: link
        force: yes
    - name: "Link doom binary"
      file:
        src: "{{ home }}/.emacs.d/bin/doom"
        dest: "{{ home }}/bin/doom"
        state: link
    - name: Initialize doom
      command: "{{ home }}/bin/doom sync"
      args:
        creates: "{{ home }}/.doom.d/config.el"
  when: r_emacs_clone_repos is not skipped
