---
- name: Install snaps (classic)
  become: yes
  snap:
    classic: true
    name:
      - android-studio
      - intellij-idea-community
      - code
      - go
      - netbeans
      - protobuf

- name: Install snaps
  become: yes
  snap:
    name:
      - hugo
      - robo3t-snap

- name: Install node
  become: yes
  snap:
    classic: true
    channel: 13/stable
    name: node

- name: Install postman
  become: yes
  flatpak:
    name: com.getpostman.Postman

- name: Install mitmproxy
  become: yes
  pip:
    executable: pip3
    name: mitmproxy

- name: Install frida-tools
  become: yes
  pip:
    executable: pip3
    name: frida-tools

- name: Install gulp
  become: yes
  npm:
    name: gulp
    global: yes
