---
- name: Install snaps (classic)
  become: yes
  snap:
    classic: true
    name:
      - android-studio
      - intellij-idea-community
      - code
      - go
      - netbeans
      - protobuf

- name: Install snaps
  become: yes
  snap:
    name:
      - hugo
      - robo3t-snap

- name: Install node
  become: yes
  snap:
    classic: true
    channel: 13/stable
    name: node

- name: Install flatpaks
  become: yes
  flatpak:
    name: com.getpostman.Postman

- name: Install pip packages
  become: yes
  pip:
    executable: pip3
    name: "{{ item }}"
  with_items:
    - mitmproxy
    - frida-tools

- name: Install npm packages
  become: yes
  npm:
    name: gulp
    global: yes
