---
- name: Install snaps (classic)
  become: yes
  snap:
    classic: true
    name:
      - android-studio
      - netbeans
      - protobuf

- name: Install snaps
  become: yes
  snap:
    name: robo3t-snap

- name: Install node
  become: yes
  snap:
    classic: true
    channel: 13/stable
    name: node

- name: Install flatpaks
  become: yes
  flatpak:
    name: "{{ item }}"
  with_items:
    - com.getpostman.Postman

- name: Install PIP packages
  become: yes
  pip:
    executable: pip3
    name: mitmproxy

- name: Install NPM packages
  become: yes
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - gulp
