---
- name: Install packages
  become: yes
  apt:
    update_cache: yes
    names:
      - simple-scan
      - thunderbird

- name: Install snaps
  become: yes
  snap:
    classic: true
    name: filebot

- name: Install flatpaks
  become: yes
  flatpak:
    name: "{{ item }}"
  with_items:
    - org.jdownloader.JDownloader
    - org.qbittorrent.qBittorrent
