---
- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      - simple-scan

- name: Install flatpaks
  become: yes
  flatpak:
    name: "{{ item }}"
  with_items:
    - com.spotify.Client
    - com.valvesoftware.Steam
    - org.mozilla.Thunderbird
    - org.qbittorrent.qBittorrent
    - tv.kodi.Kodi
