---
- name: Install CLI tools
  become: yes
  apt:
    update_cache: yes
    name:
      - adb
      - build-essential
      - dos2unix
      - git
      - gitk
      - gocr
      - htop
      - imagemagick
      - mkvtoolnix
      - nmap
      - p7zip-full
      - pwgen
      - rclone
      - ripgrep
      - rsync
      - tidy
      - tmux
      - unrar
      - uuid
      - wakeonlan

- name: Install X tools
  become: yes
  apt:
    update_cache: yes
    name:
      - weston
      - xclip
      - xserver-xephyr
      - xwayland

- name: Install GUI tools
  become: yes
  apt:
    update_cache: yes
    name:
      - baobab
      - gparted

- name: Install snaps
  become: yes
  snap:
    classic: true
    name: pdftk

- name: Install flatpaks
  become: yes
  flatpak:
    name: "{{ item }}"
  with_items:
    - com.skype.Client
    - com.github.tchx84.Flatseal
    - org.gimp.GIMP
    - org.remmina.Remmina
    - org.videolan.VLC
