---
- name: Install CLI tools
  become: yes
  apt:
    update_cache: yes
    name:
      - adb
      - build-essential
      - gocr
      - htop
      - imagemagick
      - mkvtoolnix
      - nmap
      - tidy

- name: Install X tools
  become: yes
  apt:
    update_cache: yes
    name:
      - weston
      - xclip
      - xserver-xephyr
      - xwayland

- name: Install GUI tools
  become: yes
  apt:
    update_cache: yes
    name:
      - baobab
      - gparted

- name: Install snaps
  become: yes
  snap:
    classic: true
    name: pdftk

- name: Install flatpaks
  become: yes
  flatpak:
    name: "{{ item }}"
  with_items:
    - com.skype.Client
    - org.gimp.GIMP
    - org.videolan.VLC
