---
- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      - ubuntu-desktop-minimal

- name: Remove unused packages
  become: yes
  apt:
    state: absent
    purge: yes
    name:
      - byobu
      - firefox

- name: Clean up
  become: yes
  apt:
    autoremove: yes
    autoclean: yes

- name: Add user
  become: yes
  user:
    name: "{{ user }}"
    comment: "{{ fullName }}"
    shell: /bin/bash
    groups: adm,cdrom,dip,lpadmin,lxd,plugdev,sudo
    append: yes

- name: Reset password
  become: yes
  command: passwd -d "{{ user }}"
