---
- name: Install flatpak
  become: yes
  apt:
    update_cache: yes
    name:
      - flatpak
      - gnome-software-plugin-flatpak

- name: Set up flatpak
  become: yes
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install docker
  become: yes
  apt:
    update_cache: yes
    name:
      - docker.io
      - docker-compose
  notify:
    - Assign docker group

- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      - git
      - gitk
