---
- name: Enable i386
  become: yes
  command: dpkg --add-architecture i386
  args:
    creates: /var/lib/dpkg/arch

- name: Install flatpak
  become: yes
  apt:
    update_cache: yes
    name:
      - flatpak
      - gnome-software-plugin-flatpak

- name: Set up flatpak
  become: yes
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install docker
  become: yes
  apt:
    update_cache: yes
    name:
      - docker.io
      - docker-compose

- name: Install python
  become: yes
  apt:
    update_cache: yes
    name:
      - python
      - python3
      - python3-pip
      - python3-pyqt5

- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      - bridge-utils
      - cifs-utils
      - cgroup-tools
      - cups
      - curl
      - dos2unix
      - lm-sensors
      - net-tools
      - openvpn
      - openvpn-systemd-resolved
      - p7zip-full
      - pwgen
      - smartmontools
      - tuptime
      - unrar
      - uuid

- name: Configure nsswitch.conf
  become: yes
  lineinfile:
    path: /etc/nsswitch.conf
    regex: "^hosts:"
    line: "hosts:          files resolve [!UNAVAIL=return] dns mdns4_minimal [NOTFOUND=return]"

- name: Configure grub
  become: yes
  block:
    - name: Set grub timeout style
      lineinfile:
        path: /etc/default/grub
        regex: "^GRUB_TIMEOUT_STYLE="
        line: "GRUB_TIMEOUT_STYLE="
    - name: Set grub timeout
      lineinfile:
        path: /etc/default/grub
        regex: "^GRUB_TIMEOUT="
        line: "GRUB_TIMEOUT=5"
    - name: Set grub recordfail timeout"
      lineinfile:
        path: /etc/default/grub
        regex: "^GRUB_RECORDFAIL_TIMEOUT=5"
        line: "GRUB_RECORDFAIL_TIMEOUT=5"

- name: Configure unattended upgrades
  become: yes
  copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Add user
  become: yes
  user:
    name: "{{ user }}"
    comment: "{{ fullName }}"
    shell: /bin/bash
    groups:
      - adm
      - cdrom
      - dip
      - docker
      - lpadmin
      - lxd
      - plugdev
      - sudo
    append: yes
  notify: Reset password

- name: Create data directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /data
    - /data/docker-home
    - /data/docker-home-overlay

- name: Create user data directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  with_items:
    - "/data/docker-home/{{ user }}"

- name: Flush handlers
  meta: flush_handlers
