---
- name: Add user
  become: yes
  user:
    name: "{{ user }}"
    comment: "{{ fullName }}"
    shell: /bin/bash
    groups: adm,cdrom,dip,lpadmin,lxd,plugdev,sudo
    append: yes
  notify: Reset password

- name: Enable i386
  become: yes
  command: dpkg --add-architecture i386
  args:
    creates: /var/lib/dpkg/arch

- name: Install flatpak
  become: yes
  apt:
    update_cache: yes
    name:
      - flatpak
      - gnome-software-plugin-flatpak

- name: Set up flatpak
  become: yes
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install docker
  become: yes
  apt:
    update_cache: yes
    name:
      - docker.io
      - docker-compose
  notify:
    - Assign docker group

- name: Install python
  become: yes
  apt:
    update_cache: yes
    name:
      - python
      - python3
      - python3-pip
      - python3-pyqt5

- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      - bridge-utils
      - cifs-utils
      - cgroup-tools
      - curl
      - dos2unix
      - lm-sensors
      - net-tools
      - openvpn
      - openvpn-systemd-resolved
      - p7zip-full
      - pwgen
      - smartmontools
      - tuptime
      - unrar
      - uuid
