---
- name: Add user
  become: yes
  user:
    name: "{{ user }}"
    comment: "{{ full_name }}"
    shell: /bin/bash
    append: yes
  register: r_base_add_user

- name: Reset password
  become: yes
  command: passwd -d "{{ user }}"
  when: r_base_add_user.changed

- name: Set up user groups
  become: yes
  user:
    name: "{{ user }}"
    groups:
      - adm
      - cdrom
      - dip
      - lpadmin
      - lxd
      - plugdev
      - sudo
    append: yes
