---
- name: Set up syncthing
  become: yes
  become_user: "{{ user }}"
  block:
    - name: Create directory
      file:
        path: "{{ home }}/.config/autostart"
        state: directory
        mode: "0755"
    - name: Autostart syncthing
      copy:
        src: syncthing.desktop
        dest: "{{ home }}/.config/autostart/syncthing.desktop"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
