---
- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      - git
      - gitk
      - rclone
      - ripgrep
      - rsync
      - tmux

- name: Install snaps
  become: yes
  snap:
    classic: true
    name: syncthing

- name: Install PIP packages
  become: yes
  pip:
    executable: pip3
    name:
      - ansible
      - ansible-lint
# - name: Set up syncthing
#   become: yes
#   become_user: "{{ user }}"
#   block:
#     - name: Create directory
#       file:
#         path: "{{ home }}/.config/autostart"
#         state: directory
#         mode: "0755"
#     - name: Autostart syncthing
#       copy:
#         src: syncthing.desktop
#         dest: "{{ home }}/.config/autostart/syncthing.desktop"
#         owner: "{{ user }}"
#         group: "{{ user }}"
#         mode: "0644"
