---
- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      - rclone
      - fish
      - fzf

- name: Install snaps
  become: yes
  snap:
    classic: true
    name:
      - syncthing
