---
- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      - git
      - gitk
      - rclone
      - ripgrep
      - rsync
      - tmux

- name: Install snaps
  become: yes
  snap:
    classic: true
    name: syncthing

- name: Install PIP packages
  become: yes
  pip:
    executable: pip3
    name:
      - ansible
      - ansible-lint

- name: Create directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "{{ home }}/.config/autostart"

- name: Autostart syncthing
  become: yes
  copy:
    src: syncthing.desktop
    dest: "{{ home }}/.config/autostart/syncthing.desktop"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
